[package]
name    = "nativis-rhi"
version.workspace = true
edition.workspace = true

[dependencies]
wgpu              = { workspace = true }
bytemuck          = { workspace = true }
thiserror         = { workspace = true }
tracing           = { workspace = true }
raw-window-handle = { workspace = true }
bitflags          = "2"
pollster          = "0.3"
