[package]
name    = "nativis-render"
version.workspace = true
edition.workspace = true

[dependencies]
nativis-core  = { workspace = true }
nativis-rhi   = { workspace = true }
thiserror     = { workspace = true }
tracing       = { workspace = true }
wgpu          = { workspace = true }
bytemuck      = { version = "1", features = ["derive"] }
