[package]
name    = "nativis-engine"
version.workspace = true
edition.workspace = true

[dependencies]
nativis-core         = { workspace = true }
nativis-event        = { workspace = true }
nativis-rhi          = { workspace = true }
nativis-render-graph = { workspace = true }
nativis-asset        = { workspace = true }
nativis-media        = { workspace = true }
nativis-ecs          = { workspace = true }
nativis-scene        = { workspace = true }
nativis-timeline     = { workspace = true }
nativis-audio        = { workspace = true }
nativis-platform     = { workspace = true }
nativis-plugin       = { workspace = true }
thiserror            = { workspace = true }
tracing              = { workspace = true }
winit                = { workspace = true }
anyhow               = { workspace = true }
